// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaHUU2QVcaPG9hn0TLar6_sxS9160ruuU',
    appId: '1:818439486670:web:998e098e2bc221740be49f',
    messagingSenderId: '818439486670',
    projectId: 'secondhand-marketplace-app',
    authDomain: 'secondhand-marketplace-app.firebaseapp.com',
    storageBucket: 'secondhand-marketplace-app.firebasestorage.app',
    measurementId: 'G-ENKLHJLKNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQIUvAjQyxHtm3_l1pHHSIpXOWU3lYd68',
    appId: '1:818439486670:android:d4583d5cc01329980be49f',
    messagingSenderId: '818439486670',
    projectId: 'secondhand-marketplace-app',
    storageBucket: 'secondhand-marketplace-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0OacfF_Jg3kiUzigUMrc8STKy4cvot-I',
    appId: '1:818439486670:ios:2de7d381918ddfed0be49f',
    messagingSenderId: '818439486670',
    projectId: 'secondhand-marketplace-app',
    storageBucket: 'secondhand-marketplace-app.firebasestorage.app',
    iosBundleId: 'com.example.secondhandMarketplaceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0OacfF_Jg3kiUzigUMrc8STKy4cvot-I',
    appId: '1:818439486670:ios:2de7d381918ddfed0be49f',
    messagingSenderId: '818439486670',
    projectId: 'secondhand-marketplace-app',
    storageBucket: 'secondhand-marketplace-app.firebasestorage.app',
    iosBundleId: 'com.example.secondhandMarketplaceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaHUU2QVcaPG9hn0TLar6_sxS9160ruuU',
    appId: '1:818439486670:web:1b8f90e74e75b69e0be49f',
    messagingSenderId: '818439486670',
    projectId: 'secondhand-marketplace-app',
    authDomain: 'secondhand-marketplace-app.firebaseapp.com',
    storageBucket: 'secondhand-marketplace-app.firebasestorage.app',
    measurementId: 'G-LJMP8EVBVV',
  );
}
